### ISSUE TITLE
I want to check the expiration date of SDL

### ISSUE THREAD

**Issue by takasead** [adobe/adobe-license-decoder.rs#13]
This is a very useful tool. Thank you.
Please tell me how to use this tool.

I installed SDL on my PC.
The following command will tell you the installation date and time of the installed product.
>adobe-license-decoder.windows_x86_64.exe

For FRL, you can find the expiration date with "-vv" as an option.
Is there a way in SDL to check for such an expiration date?

I'm sorry if the posting location is wrong.

**Comment by adobeDan** [comment]
Hi @takasead, sorry to take so long to get back to you.

SDL does not use cached licenses the way FRL does: the user must be online when logging in and the license is only kept as long as the user is logged in.  So there is no cached expiration date associated with the license.

If you are looking for what the expiration date of the SDL license is, you will need to check the Admin Console (which shows all the license expiration dates).

Hope this helps.
