### ISSUE TITLE
Clearer error message when no Adobe Apps are installed

### ISSUE THREAD

**Issue by Daz-wallace** [adobe/adobe-license-decoder.rs#4]
**Why do you need this feature? Please describe.**
When running the binary on a version of macOS without an OperatingConfigs file/directory, this shows the below error:
```
thread 'main' panicked at 'No such file or directory (os error 2): /Library/Application Support/Adobe/OperatingConfigs', src/main.rs:24:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Describe the solution you'd like**
Instead it would be nice if it could return a clearer output, perhaps something like:
```
Error: Item not found at /Library/Application Support/Adobe/OperatingConfigs
Confirm device has an Adobe application and licenese installed 
```

**Describe alternatives you've considered**
N/A

**Additional context**
I fully appreciate that the onus is on the administrator to understand the output and it may not make sense to run this on devices without an Adobe application installed, but there is a possibility of using this tool within a reporting solution and a nicer output would be cool 😊 

Thanks again for this!

**Comment by adobeDan** [comment]
Hi @Daz-wallace I agree this is a confusing error message.  I will try to get it cleaned up.  @adorton-adobe Did you have someone you were trying to bring up to speed on the code base?  Feel free to reassign in case I can't get to it.
