### ISSUE TITLE
Unable to check license on SDL packages

### ISSUE THREAD

**Issue by Daz-wallace** [adobe/adobe-license-decoder.rs#5]
**Describe the bug**
I've run the tool on both an SDL, license-only package, and on a package with both Photoshop with the SDL and the too doesn't seem to be able to detect the license inside. When the package/s are deployed to a device, the tool detects the install licenses fine. 

**To Reproduce**
SDL-only package:
1. Create a package from the Adobe Admin web console with Shared Device Licensing chosen, but no other applications
2. Download the Adobe Downloader App, use this to download the zipped package/s
3. Unzip the packages
4. Run the adobe-license-decoder on the parent directory, build directory or the package itself, e.g.:
5. `./adobe-license-decoder /Users/darren/Downloads/Photoshop-SDL-Test/`
6.  `./adobe-license-decoder /Users/darren/Downloads/Photoshop-SDL-Test/Build/`
7. `./adobe-license-decoder /Users/darren/Downloads/Photoshop-SDL-Test/Build/SDL-Test_Install.pkg`
8. Output:
```
thread 'main' panicked at 'No license files found in '/Users/darren/Downloads/SDL-Test/Build/SDL-Test_Install.pkg'', src/descriptions.rs:29:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
SDL and application package:
1. Repeat the above, but for step 1, also select the latest version of Photoshop
2. Rest of the testing and output is the same.

**Observed behavior**
Output shows the binary is unable to find a license:
```
thread 'main' panicked at 'No license files found in '/Users/darren/Downloads/SDL-Test/Build/SDL-Test_Install.pkg'', src/descriptions.rs:29:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Command line output as shown on the project readme

**Operating System**
macOS Big Sur (11.2.2)

**Additional context**
I'm unsure if I'm holding it wrong, but please let me know if so!
Thanks

**Comment by adobeDan** [comment]
Hi @Daz-wallace, good catch!  We forgot that the SDL packages hide the licensing resources inside the `.ccp` descriptor file at the top level of the package, instead of putting it inside a top-level `ngl-preconditioning-data.json` file.  I will try to enhance the tool to go find the licensing resources for SDL.

Until I can get to it, a workaround is to install the package and then the tool will find the license.

**Comment by Daz-wallace** [comment]
Thanks @adobeDan (and the team) 😊

**Comment by Daz-wallace** [comment]
Hi folks,

I'm afraid I'm still seeing this error on an SDL package. The new output:

```
% /Users/darren/Downloads/adobe-license-decoder-2 /Users/darren/Downloads/Photoshop-SDL-Test/Build/Photoshop-SDL-Test_Install.pkg            
Error: No license files found in directory: /Users/darren/Downloads/Photoshop-SDL-Test/Build/Photoshop-SDL-Test_Install.pkg

Location:
    src/descriptions.rs:34:13
```

**Comment by adobeDan** [comment]
Hi Darren, the package directory to specify to the tool is the root of the unzipped package, so in this case `~darren/Downloads/Photoshop-SDL-Test`.  The license data is in the `Photoshop-SDL-Test.ccp` file that's in that root directory, along with the `Build` and `Exceptions` folders.

It's a bit of an unhappy coincidence that Adobe calls them "installation packages" and Apple calls their installer files "pkg" files.  The Adobe notion of the package is the entire zipped tree.  I'll update the README to make this clearer.

**Comment by Daz-wallace** [comment]
Aha! No worries at all. Typically on macOS, since we only need the installer package I mistakenly was running it against that. I'll update my notes this side 😊 

Thanks again for your hard work on this cool tool!
