### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by Daz-wallace** [adobe/adobe-license-decoder.rs#8]
**Why do you need this feature? Please describe.**
With Apple releasing devices running their own chips instead of Intel, and the unknown time that the Rosetta 2 translation layer will work, any software or tools written for macOS would have version run natively on arm64 devices, or ideally universal binaries. From what I understand, the ALD may be Intel only, requiring the installation of Rosetta 2 to be used on these newer devices.

**Describe the solution you'd like**
Any software or tools written for macOS would have version run natively on arm64 devices, or ideally universal binaries. 

**Describe alternatives you've considered**
N/A

**Additional context**
I may be wrong here but it looks like ADL is intel only. I'm not a 'proper' developer so I'm not sure on the exact steps this project will need in order to be universal, but I thought it worth putting this on your radar 😊

**Comment by adobeDan** [comment]
Hi @Daz-wallace, you read our minds: we were just starting to explore this.  Since we have written the decoder in pure Rust, this "should" just be a matter of building it in the correct "os-platform-hardware" triple for Apple Silicon.  Thanks for the request; it's a good nudge.

**Comment by Daz-wallace** [comment]
Happy to help 😊

**Comment by adobeDan** [comment]
Hi @Daz-wallace, we have posted a native Apple Silicon build of [release 1.4](https://github.com/adobe/adobe-license-decoder.rs/releases/tag/v1.4).  The posted build was made by a developer; we will keep this issue open until we can support Apple Silicon builds as part of our CI/CD pipeline.

**Comment by adobeDan** [comment]
The only way we can support Apple Silicon in CI/CD right now is with self-hosted runners on physical machines, and that's not a good idea in a public repo.  Progress on this issue is gated by waiting for GitHub-hosted runners to support these machines.  Until then we'll just do a developer build on every release.

**Comment by adobeDan** [comment]
OK, turns out there is a way to build `aarch64-apple-darwin` binaries on Catalina machines (macOS 10.15).  So I can now integrate this into our CI scripts.
